### ISSUE TITLE
agent configuration help

### ISSUE THREAD

**Issue by wolfman2g1** [Solvik/netbox-agent#142]
I'm pretty embarrassed to ask this but I've spent hours trying to sort this out with no luck. 

I get
`ValueError: get() returned more than one result. Check that the kwarg(s) passed are valid for this endpoint or use filter() or all() instead.`
when running python3 -m netbox_agent.cli -c ./agent.yaml --register 

Here is the /etc/qualification file ( where I suspect the real issue is)

DATACENTER: 

id: dmin-1 # I've also tried setting this to the id number in the data base (1)

agent.yaml

```
 # Netbox configuration

netbox:

url: 'http://netbox'

token: xxxx

# Network configuration

network:

 # Regex to ignore interfaces  

 ignore_interfaces: "(dummy.*|docker.*)"

 # Regex to ignore IP addresses

 ignore_ips: (127\.0\.0\..*)

 # enable auto-cabling by parsing LLDP answers

 lldp: true

## Enable virtual machine support  

# virtual:

#   # not mandatory, can be guessed

#   enabled: True

#   # see https://netbox.company.com/virtualization/clusters/

#   cluster_name: my_vm_cluster

# Enable datacenter location feature in Netbox

datacenter_location:

driver: "cmd:cat /etc/qualification | tr [a-z] [A-Z]"

regex: "DATACENTER: (?P<datacenter>[A-Za-z0-9]+)"

# driver: 'cmd:lldpctl'

# regex: 'SysName: .*\.([A-Za-z0-9]+)'

#

# driver: "file:/tmp/datacenter"

# regex: "(.*)"

# Enable rack location feature in Netbox

rack_location:

# driver: 'cmd:lldpctl'

# match SysName: sw-dist-a1.dc42

# regex: 'SysName:[ ]+[A-Za-z]+-[A-Za-z]+-([A-Za-z0-9]+)'

#

# driver: "file:/tmp/datacenter"

# regex: "(.*)"

# Enable local inventory reporting  

inventory: true
```
