### ISSUE TITLE
Method "DELETE" not allowed

### ISSUE THREAD

**Issue by ecoutinho** [Solvik/netbox-agent#175]
**Describe the bug**
On netbox-2.9.8, while running a update-inventory of a existing Virtual Machine, it tries to delete an interface and fails with the error:
```
DEBUG:urllib3.connectionpool:https://x.x.x.x:443 "DELETE /api/virtualization/interfaces/ HTTP/1.1" 405 43 
pynetbox.core.query.RequestError: The request failed with code 405 Method Not Allowed: {'detail': 'Method "DELETE" not allowed.'}
```
The token used has the option "Write enabled Permit create/update/delete operations using this key" and belongs to a user which has "superuser status".

**Expected behavior**
I would expect it to delete the interface and add a new one.

**Configuration file**
```
netbox:                                                
 url: "https://x.x.x.x"                          
 token: "__________b8acba8e44b0cb4943f2136779b959"     
 ssl_verify: false                                     
network:                                               
  ignore_interfaces: "(dummy.*|docker.*|lo|loopback)"  
  ignore_ips: (127\.0\.0\..*)                          
  lldp: true                                           
virtual:                                               
  enabled: True                                        
  cluster_name: xxx
inventory: true
```                                        

**Environment:**
 - OS: CentOS 8
 - Netbox agent version: master, v0.6.2

**Additional context**
The server logs the request as:
"DELETE /api/virtualization/interfaces/ HTTP/1.1" 405 43 "-" "python-requests/2.24.0" "-"
