### ISSUE TITLE
netbox_agent: error: Problems parsing config :: while parsing a block mapping

### ISSUE THREAD

**Issue by mariano-daniel** [Solvik/netbox-agent#299]
**Describe the bug**
```
netbox_agent: error: Problems parsing config :: while parsing a block mapping
  in "<unicode string>", line 2, column 1:
    netbox:
    ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 4, column 2:
     token: 'secrettoken'
     ^
```

**Expected behavior**
Start netbox_agent

**Configuration file**
```
# Netbox configuration
netbox:
  url: 'http://192.168.0.86'
 token: 'secrettoken'
 # uncomment to disable ssl verification
 # ssl_verify: false
 # uncomment to use the system's CA certificates
 # ssl_ca_certs_file: /etc/ssl/certs/ca-certificates.crt

# Network configuration
network:
  # Regex to ignore interfaces
  ignore_interfaces: "(dummy.*|docker.*)"
  # Regex to ignore IP addresses
  ignore_ips: (127\.0\.0\..*)
  # enable auto-cabling by parsing LLDP answers
  lldp: true

#
# You can use these to change the Netbox roles.
# These are the defaults.
#
#device:
# chassis_role: "Server Chassis"
# blade_role: "Blade"
# server_role: "Server"
# tags: server, blade, ,just a comma,delimited,list
# custom_fields: field1=value1,field2=value2#
#
# Can use this to set the tenant
#
#tenant:
# driver: "file:/tmp/tenant"
# regex: "(.*)"

## Enable virtual machine support
# virtual:
#   # not mandatory, can be guessed
#   enabled: True
#   # see https://netbox.company.com/virtualization/clusters/
#   cluster_name: my_vm_cluster

# Enable datacenter location feature in Netbox
datacenter_location:
 driver: "cmd:cat /etc/qualification | tr [A-Z] [a-z]"
 regex: "datacenter: (?P<datacenter>[A-Za-z0-9]+)"
# driver: 'cmd:lldpctl'
# regex: 'SysName: .*\.([A-Za-z0-9]+)'
#
# driver: "file:/tmp/datacenter"
# regex: "(.*)"

# Enable rack location feature in Netbox
rack_location:
# driver: 'cmd:lldpctl'
# match SysName: sw-dist-a1.dc42
# regex: 'SysName:[ ]+[A-Za-z]+-[A-Za-z]+-([A-Za-z0-9]+)'
#
# driver: "file:/tmp/datacenter"
# regex: "(.*)"

# Enable local inventory reporting
inventory: true

```

**Environment:**
- Debian GNU/Linux 12 (bookworm)
 - Netbox agent version : Netbox agent does not allow for --version or -v

**Additional context**
I've also added Netbox API token as "token" value, since the instructions do not really explain where to get this token frm, nevertheless that did not work either.
